### ISSUE TITLE
Generate CSV with manuscript publication dates (poa and vor)

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#18]
This part of #1

Get POA (Publication on Acceptance) and VOR (Version of Record) timestamps from Observer and generate CSV for it.

There is no separate 'Define CSV' task as there are only two columns (beside the `msid`).

**Comment by seanwiseman** [comment]
https://observer.elifesciences.org/report/latest-articles returns a list of items in the format of:
```xml
<item>
  <title>
  Loss of <i>Atoh1</i> from neurons regulating hypoxic and hypercapnic chemoresponses causes neonatal respiratory failure in mice
  </title>
  <link>https://elifesciences.org/articles/38455</link>
  <description>
  <i>Atoh1</i>-null mice die at birth from respiratory failure, but the precise cause has remained elusive. Loss of <i>Atoh1</i> from various components of the respiratory circuitry (e.g., the retrotrapezoid nucleus (RTN)) have so far produced at most 50% neonatal lethality. To identify other <i>Atoh1</i>-lineage neurons that contribute to postnatal survival, we examined parabrachial complex neurons derived from the rostral rhombic lip (rRL) and found that they are activated during respiratory chemochallenges. <i>Atoh1</i>-deletion from the rRL does not affect survival, but causes apneas and respiratory depression during hypoxia, likely due to loss of projections to the preBötzinger Complex and RTN. <i>Atoh1</i> thus promotes the development of the neural circuits governing hypoxic (rRL) and hypercapnic (RTN) chemoresponses, and combined loss of <i>Atoh1</i> from these regions causes fully penetrant neonatal lethality. This work underscores the importance of modulating respiratory rhythms in response to chemosensory information during early postnatal life.
  </description>
  <author>hzoghbi@bcm.edu (Huda Y Zoghbi)</author>
  <author>hzoghbi@bcm.edu (Meike E van der Heijden)</author>
  <guid isPermaLink="false">https://dx.doi.org/10.7554/eLife.38455</guid>
  <category>Developmental Biology</category>
  <category>Neuroscience</category>
  <pubDate>Wed, 04 Jul 2018 00:00:00 +0000</pubDate>
  <dc:date>2018-07-04T00:00:00Z</dc:date>
</item>
```

So does the `csv` require the `<pubDate>` and `<dc:date>` values? making the columns in the `csv` file `msid`, `pub_date` and `dc_date`?

Also, will this generation always be all articles? or a defined range? either way we will have to crawl through the articles.

**Comment by de-code** [comment]
You can use https://observer.elifesciences.org/report/published-research-article-index.csv which returns exactly what we need (just need to add the CSV headers and convert the dates)

**Comment by seanwiseman** [comment]
Ah, excellent!

**Comment by lsh-0** [comment]
I think it's cool that **anybody** is finally using that report. I think the manually created and edited version is still being passed around internally. It was one of the first reports I created for observer and the main reason for creating something like observer in the first place. And then nobody used it for years. It's funny, laugh.

**Comment by lsh-0** [comment]
> (just need to add the CSV headers and convert the dates)

oh I see what you're doing now

![reinventingthewheel](https://user-images.githubusercontent.com/2142748/44133918-797274fa-a0a1-11e8-90e9-ae206677c149.jpg)

**Comment by de-code** [comment]
> oh I see what you're doing now

I am assuming that was related to converting the dates? We could maybe have another 'referendum' ;-)

**Comment by lsh-0** [comment]
no, it was related to using observer as a source of data, when observer itself is doing what this prototype is attempting to do.

**Comment by de-code** [comment]
The publication dates weren't initially in scope but we are importing the data here so that we can join with them to produce the editorial report. I believe observer doesn't import all of the data from EJP that we need.
Should add that to the design document as a consideration.

**Comment by lsh-0** [comment]
> observer doesn't import all of the data from EJP

nope, public data only
