### ISSUE TITLE
Create dummy CSV for senior editor workloads report

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#21]
Part of #2 to create a dummy CSV that helps #15 

Created CSV with the following columns:

* person_id
* person_name: full name of senior editor
* decision_month_timestamp: the timestamp for the start of the month
* decision_year: just the year
* decision_month: just the number (int)
* decision_count: number of decisions made within that month
* rejected_count: number of decisions that were rejections

**Comment by BlueReZZ** [comment]
This can be closed as it has been superceded by the new XML to JSON to BigQuery workflow
