### ISSUE TITLE
Create draft Submission and Publication report

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#22]
Create a draft Submission and Publication report to inform us on the required data and format of the view.

CSV coming from #24

**Comment by de-code** [comment]
@BlueReZZ Should this be considered as done?

**Comment by BlueReZZ** [comment]
Yes, as it's here https://datastudio.google.com/open/1GOxToVX4FLYRJRRn-COXrVwuEElBmseK (Note only visible inside eLife for the moment since it's not real data)
