### ISSUE TITLE
Add support for `-Appeal` and `Rn` suffix in manuscript number

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#31]

**Comment by seanwiseman** [comment]
@de-code do you have more info on the requirements for this?

**Comment by de-code** [comment]
The _manuscript-number_ field might have an `-Appeal` suffix, e.g.:

`<manuscript-number>01-02-2017-RA-eLife-12345R1-Appeal</manuscript-number>`

In that case it should still be able to extract the _msid_ `12345` (I believe it didn't). The issue should probably be extended handle the `R1` etc (revision 1) suffix.

**Comment by seanwiseman** [comment]
> `<manuscript-number>01-02-2017-RA-eLife-12345R1-Appeal</manuscript-number>`

So in the above case the `R1` should also be stripped? and also any `R*`?

**Comment by de-code** [comment]
> So in the above case the `R1` should also be stripped? and also any `R*`?

Yes

(that will be less likely an issue with regular manuscripts because we are only looking for the first _manuscript-number_ field but the appeal can come in as a separate XML starting with _R1_)
