### ISSUE TITLE
Allow temp zip output directory to be created in container

### ISSUE THREAD

**Issue by seanwiseman** [elifesciences/data-pipeline#37]
Currently, you can no longer pass a zip file as a `--source-zip` arg to `csv_generator` due to the fact the `DEFAULT_ZIP_OUTPUT_DIR` cannot be created within the container.

**Comment by de-code** [comment]
Is that via Docker only?

**Comment by seanwiseman** [comment]
Yes, I mention container in the title, but have now added it to the description as well to be clearer.

**Comment by de-code** [comment]
Apologies, must have skipped reading the title..

We could just change the directory to either be within the `csv-generator` directory (i.e. not `../`) or temp directory. The other alternative is not to extract but just extract on the fly but should probably be another 'enhancement'.
