### ISSUE TITLE
Create orchestration prototype (e.g. Airfow)

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#40]
We need a prototype that would watch a bucket and triggers the processing whenever there is a new file (moving processed files away if necessary)

We may setup a separate copy from the shared s3 bucket to a project specific "incoming" bucket.

We could also consider Pachyderm.

(we should be able to then deploy that in production to populate a database and keep it updated)

These are the tasks we need:

* Monitor S3 or GCP bucket ('incoming') for new zip files
* Call `csv-manager` with new zip file
* Call `db-manager` with generated CSV files

If necessary (not sure):

* We need to remove/move the file at the end, in which case we need to:
* Automatically copy new files from the original bucket to a temporary incoming bucket

There also needs to be a facility to backfill the processing (e.g. if we need the temporary bucket then we could manually just copy the zip files to the bucket)

**Comment by seanwiseman** [comment]
After some prototyping, I am clearer on how we could implement this.

@de could I get some feedback on whether these DAG tasks seems logical?

- Monitor S3 bucket for changes (if we want to also support GCP then it would require a different sensor)
- Get file key (the sensor above does not return what has changed/arrived, just that something has, so this will actually get the new file key)
- Download new zip
- Move original zip to `archive` / `backfill` bucket (leaving the monitored bucket now empty)
- Call `csv-manager` with new zip
- Call `db-manager` with generated CSV files
- Complete

**Comment by seanwiseman** [comment]
> In that case we still need something that monitors the shared S3 bucket and copies only new files to a project specific bucket. I guess that would be outside Airflow?

Could just be another `DAG` that monitors and copies the files from the shared bucket? but yes it could also be outside of `airflow` as well.

> It may also be that there are multiple 'new' zip files (e.g. in the backfill case). Would the DAG tasks handle that?

Sorry, the names should be:

- Download new zip(s)
- Call `csv-manager` with the new zip(s)

It should handle multiple zip files.

**Comment by de-code** [comment]
> Could just be another DAG that monitors and copies the files from the shared bucket? but yes it could also be outside of airflow as well.

That is what I wasn't sure about. If we can have that in the DAG then do we need the separate project specific bucket? i.e. could we just process the new zips? And if we can do that, how would we do the backfill? With a project specific bucket we could just manually copy the files back. And if it isn't part of the DAG, what would we use instead? I believe AWS has some tools to do it. Alternatively we could have our own code (but it would be another layer to maintain).

**Comment by seanwiseman** [comment]
I think a separate project-specific bucket + a backfill store bucket makes sense and like you say, would make backfilling easy.

**Comment by de-code** [comment]
Okay, sounds good. I've added #63 as a separate task. Initially it would already be great to be able to test that by manually copying the files.

**Comment by seanwiseman** [comment]
Part one completed in [#67](https://github.com/elifesciences/data-pipeline/pull/67).

**Comment by seanwiseman** [comment]
Final part completed in [#72](https://github.com/elifesciences/data-pipeline/pull/72)
