### ISSUE TITLE
Deploy first container to demo environment

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#41]
Deploy the project to production.

This depends on #40 (otherwise it wouldn't do much)

Preferred cloud provider might be Google for this.

Phase 1 of https://files.slack.com/files-pri/T025LBBQS-FBS4H741F/img_20180718_143226556_hdr.jpg

- [x] web server container
- [x] `postgres` stateless container
- [x] `redis` stateless container
- [x] `nginx` container for authentication
- [x] formula repository
- [x] `prod-data-pipeline` pipeline
- [x] formula pipeline to test changes

**Comment by giorgiosironi** [comment]
Given all of this is built as container images, how easy it is to set up a GKE cluster to run them?
There are some databases involved however, not sure if running them as containers is the most stable option.

**Comment by de-code** [comment]
As I understand it is fairly straightforward to setup a Kubernetes cluster and deploy to it. Alternatively one can also create a VM from docker container.

You're probably right that it would probably be better to use Google's Cloud SQL for the main database. I am not sure about Airflow's database. @seanwiseman does that only contain temporary state or should we keep that around?

**Comment by seanwiseman** [comment]
> does the Airflow database need a database migration strategy (when upgrading Airflow) or is that automatic?

You could tinker with it if you wanted to (not sure why at this point), but no, it handles its own migrations so any changes to any data models it owns (from possible updates) should be handled automatically.

**Comment by de-code** [comment]
Okay, great. (No, I certainly don't fancy tinkering with it)

**Comment by giorgiosironi** [comment]
Splitting off #88 and #89, and renaming to `demo` the environment since it will be built manually rather than with fully integrated infrastructure automation.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/data-pipeline-formula is a sample deployment. Will try to put it into a pipeline in some way, since we want to be able to deploy new versions.

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/prod-data-pipeline/ is the prototype that will clone the formula, and apply it again. The formula is hardcoded to use the `latest` image, parameterizing that will require more work.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/builder-base-formula/pull/156 and https://github.com/elifesciences/elife-alfred-formula/pull/9 will make Alfred (with a bit of secret configuration) able to interact with the cluster for deployment.

**Comment by giorgiosironi** [comment]
Should probably tackle https://github.com/elifesciences/data-pipeline/issues/92 before the other slices.

**Comment by giorgiosironi** [comment]
PR built successfully https://alfred.elifesciences.org/job/pull-requests-projects/job/data-pipeline-formula/job/PR-1/
New pipeline https://alfred.elifesciences.org/job/formula/job/data-pipeline-formula/

Not perfect by any means, but will show all the pains of updating infrastructure where present.
