### ISSUE TITLE
Convert csv-generator to a hostable Python package

### ISSUE THREAD

**Issue by seanwiseman** [elifesciences/data-pipeline#54]
This will be required due to its use in `airflow`.

It's easier and cleaner to just install this as a dependency from `pypi` inside the `airflow` container(s) rather than copying the source in.

**Comment by de-code** [comment]
I am thinking whether we would want to have some end2end tests in CI using the current version. I guess we could locally install the individual projects to bypass `pypi`?

**Comment by seanwiseman** [comment]
Yer, we can just install via the `setup.py` locally or we could just use `pypi`, after all the end2end tests would presumably have to install other dependencies from `pypi`. I suppose it depends on how the tests are structured.

**Comment by seanwiseman** [comment]
Was done in [#67](https://github.com/elifesciences/data-pipeline/pull/67).

Note: it is not currently hosted on `pypi` but it is in a state 'to be' hosted now.
