### ISSUE TITLE
Allow for db configuration in db-manager

### ISSUE THREAD

**Issue by seanwiseman** [elifesciences/data-pipeline#56]
@de

Currently, the `db-manager` package exposes configuration for its target db via [environment variables](https://github.com/elifesciences/data-pipeline/blob/e93e2cea730a4fbc3b955f60a2017172d2dc6ed8/db-manager/db_manager/__main__.py#L42). This is fine for its current use, but for use within environments which may have multiple databases for example, a more flexible and clearer configuration layer is required. This may just mean using more specific env var names to avoid clashes.

The requirement comes from the need to use this package from within a container separate from the external db we are targetting.

**Comment by seanwiseman** [comment]
This configuration should also be added to the docs.

**Comment by de-code** [comment]
What are you proposing?

Could you please elaborate a bit more on the multiple database use-case you were thinking of? The `db-manager` would be used to populate multiple databases? Or you think when running `db-manager` locally (without Docker) then the current environment variable names could likely clash?

**Comment by seanwiseman** [comment]
> What are you proposing?

I think just more bespoke env var names might be fine e.g. `DB_MGR_HOST`, `DB_MGR_PORT` something like that. Alternatively, you could just allow `managed_connection` func to take the values as arguments so that the package does not know how to configure itself, it has to have the values provided.

> Or you think when running db-manager locally (without Docker) then the current environment variable names could likely clash?

Yes, that was more my thinking.

**Comment by de-code** [comment]
Okay, makes sense.
