### ISSUE TITLE
Refactor importable code out of `db_manager.__main__`

### ISSUE THREAD

**Issue by seanwiseman** [elifesciences/data-pipeline#65]
All functions and classes apart from `main()` defined in `db_manager.__main__` need to be moved into a sperate module.

Without doing so, importing and using the `db_manager` becomes an issue when using it as a library (e.g. in Airflow).

`__main__` should just provide the main entry point for command line use.

Pinging @de.

**Comment by de-code** [comment]
How would you interface with the project? What would be the expected function signature for the Airflow integration?

**Comment by seanwiseman** [comment]
Well at present I only need to call `process_source_dir` and use the `managed_connection` context manager.

**Comment by de-code** [comment]
I will do that now. I will move `managed_connection` (and related) to `db_manager.database` and `process_source_dir` (etc) to `db_manager.processing`.
