### ISSUE TITLE
Convert assigned senior editor to CSV

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#73]
We need the _person-id_ of the assigned _senior-editor_ exported to CSV.

The XML models the senior editor as a list. In practise there will however be only one senior editor (or none). Apparently that would also be the case for other publishers.

Therefore we could either create a `<time>_manuscript_version_senior_editors.csv` or add a `senior-editor-person-id` to the `<time>_versions.csv`

(see milestone for context)

**Comment by de-code** [comment]
Okay, Andy reconfirmed that seems to make sense for all publishers.

**Comment by seanwiseman** [comment]
Resolved in [#79](https://github.com/elifesciences/data-pipeline/pull/79).
