### ISSUE TITLE
Convert assigned reviewing editor to CSV

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#74]
We need the _person-id_ of the assigned _reviewing-editors_ exported to CSV.

The XML models the reviewing editor (`editor` field) as a list. In practise there will however be only one reviewing editor (or none). Apparently that would also be the case for other publishers.

Therefore we could either create a `<time>_manuscript_version_reviewing_editors.csv` or add a `reviewing-editor-person-id` to the `<time>_versions.csv`

(see milestone for context)

**Comment by seanwiseman** [comment]
Resolved in [#79](https://github.com/elifesciences/data-pipeline/pull/79).
